<?php
include("variables.php");
/**
 * Created by Mumara Team
 * Date: 07/16/2020
 */

$lang['page']['title']                     = 'Security';
$lang['page']['description']               = 'Secure your account by changing your password frequently and reviewing the recent activities';

/*-------------- 1. Security -> Password Section ----------------*/
$lang['section1']['title']                 = 'Password';
$lang['section1']['description']           = 'Change your account password often to prevent unauthorized access to your account.';
$lang['section1']['Change_Password']       = 'Change Password';

/*-------------- 2. Security -> Allowed IP Address Section ----------------*/
$lang['section2']['title']                           = 'Allowed IP Address';
$lang['section2']['description']                     = 'Restrict access to your account by adding a range of trusted IP addresses.';
$lang['section2']['Add_ip_Address']                  = 'Add Allowed IP Address';
$lang['section2']['Ensure_static_IP_address']        = 'Ensure that the IP address you provide is a static IP address. Since the dynamic IP addresses change and you might get locked out of your account.';
$lang['section2']['further_sign_ins']                = 'All further sign-ins will only be permitted from this IP range.';
$lang['section2']['current_IP_address']              = 'Add your current IP address';
$lang['section2']['static_IP_address']               = 'Add a static IP address';
$lang['section2']['Add_IP_range']                    = 'Add an IP range';
$lang['section2']['SubNet']                          = 'Add a subnet';
$lang['section2']['Your_IP_address']                 = 'Your IP address';
$lang['section2']['invalid']['subnet']               = 'Invalid SubNet';
$lang['section2']['IP_Name']                         = 'IP Name';
$lang['section2']['friendly_ip_name']                = 'Please enter a friendly ip name';

/*-------------- 3. Security -> Active Sessions Section ----------------*/
$lang['section3']['title']                 = 'Active Sessions';
$lang['section3']['description']           = 'View and manage all of your active sessions.';

/*-------------- 4. Security -> Two-Factor Authentication Section ----------------*/
$lang['section4']['title']                        = 'Two-Factor Authentication';
$lang['section4']['description']                  = 'Each time you sign in to your Google Account, you\'ll need your password and a verification code';
$lang['section4']['protect_your_account']         = 'Protect your account with 2-Step Verification';
$lang['section4']['multi_factor_authentication']  = 'Enable multi-factor authentication.<br>Secure your '.$siteTitle.' account.';
$lang['section4']['Started_Time']                 = 'Started Time';
$lang['section4']['Backup_Code']                  = 'Your Backup Code is';
$lang['section4']['Get_Started']                  = 'Get Started';
$lang['section4']['2fa_desc']                     = 'Two-Factor authentication adds an extra layer of protection of your account. Once enabled, every time you sign in to the :title, you \'ll need to enter both username &amp; password as well as a second factor such as a security code.';
$lang['section4']['One_Time_Password']                     = ' <h4>Time-Based One-Time Password</h4>
                        <p>This authentication option get`s it`s second factor using a time based algorithm. Your
                            mobile can be used to generate the codes. if you don\'t already have an app that can do
                            this, we recommend Google Authentication which is available for IOS, Android and Windows
                            mobile devices.</p>
                        <p>To configure your authentication app:</p>
                        <ul class="auth-list">
                            <li>Begin by selected to add a new time based token</li>
                            <li>Then use your app to scan the qr-code below, or alternatively enter this secret key
                                manually:<br>
                                <div id=""></div>
                            </li>
                        </ul>';
$lang['section4']['MANUAL_ENTRY']                         = 'MANUAL ENTRY';
$lang['section4']['ignore_spaces']                        = 'Spaces don\'t matter';
$lang['section4']['Verification_Step']                    = 'Verification Step';
$lang['section4']['Enter_Security_code']                  = 'Enter the Security code generated by your authenticator app and we`ll make sure it`s configured correctly before enabling it.';
$lang['section4']['disable_2fa']                          = 'To disable Two-Factor Authentication please confirm your password in the field below.';
$lang['section4']['Password_Reset_Request']               = 'Password Reset Request';
$lang['section4']['Enter_email_address']                  = 'Enter your email address in the space below and we will mail you the password reset instructions';

/*-------------- Messages ----------------*/
$lang['message']['Session_Account_removed']                 = 'You don\'t have any session accounts';
$lang['message']['Session_Account_removed']                 = 'Session Account <span id="sessions-name"></span> successfully removed.';
$lang['message']['atleast_characters']                 = 'Include at least 8 characters';
$lang['message']['Set_strong_password']                = 'Set a strong password to prevent unauthorized access to your account.';
$lang['message']['enter_a_valid_IP']                   = 'Please enter a valid IP address';
$lang['message']['enter_a_valid_email']                   = 'Please enter valid email address';
$lang['message']['save_2fa']                           = 'write this down on paper and keep it safe.<br>it will be needed if you ever lose your 2nd factor device or it is unavailable to you.';
$lang['message']['2fa_authentication_complete']        = 'Two-Factor Authentication Setup is Complete!';
$lang['message']['code_not_matched']                   = 'The code you entered did not match what was expected. Please try again.';
$lang['message']['verification_link_sent']             = 'Email verification link successfully sent.';
$lang['message']['ip_terminated']                      = 'IP successfully terminated.';
$lang['message']['ip_alert']                           = ' <div class="alone_current_ip"><div class="note_ip">NOTE </div><div class="ip_note_desc">Your current IP address <b>:ip</b> is not in the below IP ranges. Once you sign out, you will not be able to sign in from this IP address. Click here to add your current IP address.</div></div>';

/*-------------- General  ----------------*/

$lang['request']="Request";
$lang['device_name']="Computer";
$lang['device_time']="a few seconds ago";

return $lang;
